version: '3.7'

services:
  postgres:
    image: postgres
    container_name: jpa-exercise-db
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./db/:/var/lib/postgresql/data
    ports:
      - 5432:5432
