GET localhost:8080/api/store/all
Accept: application/json

###

GET localhost:8080/api/store/1000
Accept: application/json

###

POST localhost:8080/api/store
Accept: application/json
Content-Type: application/json

{
  "city": "Moscow",
  "name": "RussianRoulette MovieRetail",
  "id": 100,
  "staffList": [
    {
      "firstName": "Ernest",
      "lastName": "Employer",
      "hireDate": "2021-01-05",
      "salary": 1200,
      "sales": [
        {
          "customer": {
            "firstName": "Cleveland",
            "lastName": "Client",
            "dateOfBirth": "2002-04-05",
            "place": "Niceplace",
            "street": "Nicestreet 1",
            "zip": "5050"
          },
          "movie": {
            "duration": 122.00,
            "language": "ENGLISH",
            "rating": 8.3,
            "title": "American Beauty",
            "year": 1999
          },
          "payment_date": "2021-04-05",
          "price": 24.90
        }
      ]
    }
  ]
}
